name: release-please
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    name: "Release Please"
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple

  build:
    name: "Build release binaries"
    needs: ["release-please"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - run: ./scripts/build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*

#      - name: Upload Release Artifact
#        if: ${{ steps.release.outputs.release_created }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: gh release upload  --clobber ${{ steps.release.outputs.tag_name }} ./dist/*
